Made Tests for Models
carlosmuerto/doctor_reservation_api pull request #24
Opened 2023-01-11 22:28 UTC by LokurasRlz

# Testing

Created Unit Tests for Models using Rspec and Capybara

# Issues

- close #23

2023-01-11 23:52 UTC, carlosmuerto requested changes
# Status: Change Required 🟡 🟡 🟡 
### Hi @LokurasRlz 🙋‍♀️,  

## Highlights 🌞 

✔️  Good PR title and description
✔️  Commit messages are meaningful
✔️  No linter errors

✔️  ✔️  All test are well made

## Please check the comments below

2023-01-11 23:52 UTC, carlosmuerto commented on Gemfile
> +  gem 'capybara'
capybara is for page testing and is not designed for testing API

2023-01-11 23:52 UTC, carlosmuerto commented on Gemfile.lock
> +      regexp_parser (>= 1.5, < 3.0)
don forget the bundle install after remove capybara

2023-01-11 23:52 UTC, carlosmuerto commented on spec/models/appointment_spec.rb
> +                                      user_id: @user.id, doctor_id: @doctor.id)
Use some dynamically generate a time to ensure the test is agnostic of the testing date
 in this case you case use `1.years.from_now`

```ruby 
Appointment.create(
    user: seeded_user,
    doctor: seeded_doctor,
    description: "seeded description",
    datetime_of_appointment: 1.years.from_now
)
```

remember to apply this to the other cases

2023-01-11 23:52 UTC, carlosmuerto commented on spec/models/appointment_spec.rb
> +                                    datetime_of_appointment: '2020-01-11 00:20:20.000000000 +0000')
for this case you can use a negative number 

```ruby
appointment = Appointment.new(
    user: @user, 
    doctor: @doctor, 
    description: 'abc',
    datetime_of_appointment: -1.years.from_now
)
remember to apply this to the other cases

```

2023-01-12 15:48 UTC, LokurasRlz commented
@carlosmuerto, I have already applied the required changes.

2023-01-12 16:06 UTC, carlosmuerto approved these changes
# APPROVED 🟢 🟢 🟢

2023-01-12 16:06 UTC, merged